---
title: "Statistical analysis in RStudio"
output:
  pdf_document:
    keep_tex: yes
    extra_dependencies: "subfig"
    toc: yes
    toc_depth: 2
    number_sections: yes
  html_document:
    toc: yes
    toc_depth: '2'
    df_print: paged
  word_document:
    toc: yes
    toc_depth: '2'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tinytex.verbose = TRUE)
library(knitr)
library(readxl)
library(pastecs)
library(tidyverse)
library(tinytex)
library(equatiomatic)
library(stringr)
library(ggplot2)
library(Rmisc)
```
### Abstact


# INTRODUCTION

```{r, echo=FALSE}
## Importing Data

data <- read.csv("Seal averages 2007-2010.csv", header = T)

## Converting Data to data frame
data <- data.frame(data)

# Checking first 6 six rows of data
kable(head(data))


```
```{r, echo=F}
# Checking  structure of data 
str(data)

```
```{r,echo=FALSE}
##Converting data types 

###Removing string "Summer-" from Column Summer for Better understanding 
data$Summer <- str_remove_all(data$Summer, "[summer-]")

### Converting Summer Column data type to Factor
data$Summer <- as.factor(data$Summer)

### Converting Year.Month Column data type to Factor
data$Year.Month <- as.factor(data$Year.Month)

### Converting Site Column data type to Factor

data$Site <- as.factor(data$Site)

### Converting Species Column data type to Factor
data$Species <- as.factor(data$Species)
```


```{r, echo=F}
# Checking  structure of data 
str(data)

```


# MATERIALS AND METHODS

```{r, echo=F}
## As Mention in the Section 2 Checking for Normalizes 

qqnorm(data$average.count)
```


```{r, echo=F}
## shapiro Test 

shapiro.test(data$average.count)
```
```{r, echo=F}
## So After running Shaprio test we can find the our data is not data are not significantly different from normal distribution.As Our p-value is 2.2
## We will run Kruskal-Wallis Test

kruskal.test(data$average.count, data$Summer) 
```

```{r, echo=F}
#As the p-value is less than the significance level 0.05, we can conclude that there are significant differences between the groups.

## Running pairwise wilox Test 

pairwise.wilcox.test(data$average.count, data$Summer)
```
```{r, echo=F}
## Now avoiding false-positive values for the data 
pairwise.wilcox.test(data$average.count, data$Summer,
                     p.adjust.method = "BH")
```

```{r, echo=F}

##Checking the Avg Count value difference between 2010 and 2007

plot(data$Summer, data$average.count)
```

```{r, echo=F}
## Exploring diffrence between months in 2007 using kruskal test

kruskal.test(data$average.count[data$Summer == "2007"], data$Year.Month[data$Summer == "2007"]) 
```

```{r, echo=F}
## Exploring diffrence between months in 2007 using pairwise wilox Test 

pairwise.wilcox.test(data$average.count[data$Summer == "2007"],data$Year.Month[data$Summer == "2007"],
                     p.adjust.method = "BH")
```

```{r, echo=F}
## Comparing species abundance

kruskal.test(data$average.count, data$Species)

```

```{r, echo=F}
## Plotting Seal avg count vs Species


plot(data$average.count ~ data$Species)
```

```{r, echo=F}

## Calculating for all years

kruskal.test(data$average.count, data$Species) 

```

```{r, echo=F}
## Now avoiding false-positive values for the data 
pairwise.wilcox.test(data$average.count, data$Species,
                     p.adjust.method = "BH")
```

```{r, echo=F}
## Calculating for Year 2007


kruskal.test(data$average.count[data$Summer == "2007"], data$Species[data$Summer == "2007"]) 
```

```{r, echo=F}
## Exploring diffrence between months in 2007 using pairwise wilox Test 

pairwise.wilcox.test(data$average.count[data$Summer == "2007"],data$Species[data$Summer == "2007"],
                     p.adjust.method = "BH")
```

```{r, echo=F}
## Calculating for Year 2008


kruskal.test(data$average.count[data$Summer == "2008"], data$Species[data$Summer == "2008"]) 
```

```{r, echo=F}
## Exploring diffrence between months in 2007 using pairwise wilox Test 

pairwise.wilcox.test(data$average.count[data$Summer == "2008"],data$Species[data$Summer == "2008"],
                     p.adjust.method = "BH")
```

```{r, echo=F}

## Calculating for Year 2009


kruskal.test(data$average.count[data$Summer == "2009"], data$Species[data$Summer == "2009"]) 
```

```{r, echo=F}
## Exploring difference between months in 2007 using pairwise wilox Test 

pairwise.wilcox.test(data$average.count[data$Summer == "2009"],data$Species[data$Summer == "2009"],
                     p.adjust.method = "BH")
```

```{r, echo=F}

## Calculating for Year 2010


kruskal.test(data$average.count[data$Summer == "2010"], data$Species[data$Summer == "2010"]) 

```

```{r, echo=F}
## Exploring difference between months in 2010 using pairwise wilox Test 

pairwise.wilcox.test(data$average.count[data$Summer == "2010"],data$Species[data$Summer == "2010"],
                     p.adjust.method = "BH")
```


# RESULTS


# DISCUSSION


### REFERENCES